[workspace]
members = [
    "cli",
    "executor",
    "inspect",
    "primitives",
    "rpc",
    "runtime",
]
[profile.release]
panic = "unwind"

[patch.crates-io]
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "dev" }